openapi: 3.0.3
info:
  title: LVT API
  description: Public REST API
  version: 1.0.1
servers:
  - url: 'https://api.lvt.com/v1'
    description: Production beta version
security:
  - OAuth2: [ ]
tags:
  - name: Cameras
    description: Operations on cameras
  - name: LiveUnits
    description: Operations on LiveUnits
  - name: Locations
    description: Operations on locations
  - name: Webhooks
    description: Operations on webhooks
  - name: PublicKeys
    description: Operations related to outbound message verification
  - name: Talkdown
    description: Operations related to Partner Talkdown

paths:
  /liveUnits:
    get:
      operationId: GetLiveUnits
      security:
        - OAuth2: [ account.liveUnits.manage ]
      tags:
        - LiveUnits
      summary: This endpoint returns all the live units accessible by the specified client.
      description: >
        **Phase 1**:
        List of liveUnits for the user's client
  /liveUnits/{liveUnitId}:
    get:
      operationId: GetLiveUnit
      security:
        - OAuth2: [ account.liveUnits.manage ]
      tags:
        - LiveUnits
      summary: Details for the specified live unit.
      description: >
        **Phase 1**:
        Details for the specified live unit.
  /liveUnits/{liveUnitId}/callInfo:
    get:
      operationId: GetLiveUnitCallInfo
      tags:
        - LiveUnits
      summary: Get information on how to make a call to the live unit
      description: >
        **Phase 2**: 
        Get information on how to make a call to the live unit
  /liveUnits/{liveUnitId}/cameras:
    get:
      operationId: GetLiveUnitCameras
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - LiveUnits
      summary: List of user accessible cameras hosted by the given liveUnit.
  /liveUnits/{liveUnitId}/sounds:
    get:
      operationId: GetLiveUnitSounds
      tags:
        - LiveUnits
      summary: List of quick sounds that can be played by the live unit
      description: >
        **Phase 3**:
        List of quick sounds that can be played by the live unit
  /liveUnits/{liveUnitId}:call:
    post:
      operationId: TalkDownStart
      tags:
        - LiveUnits
        - Talkdown
      summary: Initiate a speaker talk-down call
      description: >
        Initiate a speaker talk-down call with the live unit.
  /liveUnits/{liveUnitId}/sounds/{soundId}:play:
    post:
      operationId: PlayLiveUnitSound
      tags:
        - LiveUnits
      summary: Play a quick sound from a live unit
      description: >
        **Phase 3**:
        Play a quick sound from a live unit
  /liveUnits/{liveUnitId}/lights:
    get:
      operationId: GetLiveUnitLights
      tags:
        - LiveUnits
      summary: List of lights on the live unit
      description: >
        **Phase 3**:
        List of lights on the live unit
  /liveUnits/{liveUnitId}/lights/{lightId}:toggle:
    post:
      operationId: ToggleLiveUnitLight
      tags:
        - LiveUnits
      summary: Toggle the status of a light on a live unit
      description: >
        **Phase 3**:
        Toggle the status of a light on a live unit
  /cameras/{cameraId}:
    get:
      operationId: GetLiveUnitCamera
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
      summary: Details of selected camera.
      description: >
        **Phase 1**:
        Details of selected camera.
  /cameras/{cameraId}/position:
    get:
      operationId: GetCameraPosition
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
      summary: Returns the selected camera's PTZF values
      description: >
        **Phase 1**:
        Returns the selected camera's PTZF values
    put:
      operationId: UpdateCameraPosition
      deprecated: true
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
      summary: Updates the selected camera's PTZF values
      description: >
        **This endpoint is deprecated. Use the PATCH request.**


        Updates a camera's PTZF
    patch:
      operationId: UpdateCameraPosition2
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
      summary: Updates the selected camera's PTZF values
      description: >
        Sets a camera's position relative to its current position unless the absolute query parameter is passed.


        Some camera models do not support focus. If the focus is sent, it will be ignored.
  /cameras/{cameraId}/protocols:
    get:
      operationId: GetProtocols
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
      summary: Returns list of protocols supported
      description: >
        **Phase 1**:
        Get list of protocols supported by this camera.
  /cameras/{cameraId}/streams:
    post:
      operationId: StartStream
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
        - Streams
      summary: Start a stream
      description: >
        **Phase 1**:
        Starts a stream and returns stream data for the camera
  /streams/{streamId}:checkIn:
    post:
      operationId: CheckIn
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Streams
      summary: Check in streaming for the camera
      description: >
        **Phase 1**:
        Check in streaming for the camera
  /streams/{streamId}:
    delete:
      operationId: CheckOut
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Streams
      summary: Check out streaming for the camera
      description: >
        **Phase 1**:
        Check out streaming for the camera
  /locations:
    get:
      operationId: GetLocations
      security:
        - OAuth2: [ account.locations.manage ]
      tags:
        - Locations
      summary: List of locations for the user's client
      description: >
        **Phase 1**: 
        Returns all the locations accessible by the specified client.
  /locations/{locationId}:
    get:
      operationId: GetLocation
      security:
        - OAuth2: [ account.locations.manage ]
      tags:
        - Locations
      summary: Details for the specified location.
      description: >
        **Phase 1**:
        Details for the specified location.
  /locations/{locationId}/liveUnits:
    get:
      operationId: GetLocationLiveUnits
      security:
        - OAuth2: [ account.liveUnits.manage ]
      tags:
        - Locations
      summary: List of user accessible live units at the given location.
      description: >
        **Phase 1**:
        List of user accessible live units at the given location.
  /alerts/events:
    get:
      summary: Get events
      description: Get a list of events. By default it returns all owned events, but can be filtered using the query parameters.
      tags: [Events]
  /alerts/events/{id}:
    get:
      summary: Get an event
      description: Get an event with the provided ID.
      tags: [Events]
  /alerts/events/{id}:addNote:
    post:
      summary: Create a Note
      description: Create a new Note for the event with the provided ID.
      tags: [Events]
  /alerts/events/{id}:resolve:
    post:
      summary: Resolve an event
      description: Resolve an event with the provided ID.
      tags: [Events]
  /alerts/events/{id}:assignUser:
    post:
      summary: Assign a user to an event
      description: Assign a user to an event with the provided ID.
      tags: [Events]
  /alerts/media/{mediaId}/url:
    get:
      summary: Get a signed url for media
      description: Get a signed url for the provided ID.
      tags: [Media]
  /webhooks:
    post:
      summary: Create a Webhook
      description: |-
        Create a Webhook.
        
        Upon creation, a webhook is first verified by sending a test message. The message must be responded to with a 2xx response code to be considered successful. This success is 
        prerequisite to the Webhook creation. This process can be tested using the `/webhooks:test` endpoint before committing to creating a Webhook.
      tags: [ Webhooks ]
    get:
      summary: Get Webhooks
      description: Get a list of Webhooks. By default it returns all owned Webhooks, but can be filtered using the query parameters.
      tags: [ Webhooks ]
  /webhooks/{webhookId}:
    get:
      summary: Get a Webhook
      description: Get a Webhook with the provided ID.
      tags: [ Webhooks ]
    patch:
      summary: Update a Webhook
      description: Update specific properties of a Webhook. If the property is not listed as acceptable in the request body and needs to be changed, you can delete the existing Webhook and recreate it instead.
      tags: [ Webhooks ]
    delete:
      summary: Delete a Webhook
      tags: [ Webhooks ]
  /webhooks:test:
    post:
      summary: Test a Webhook
      description: |-
        Send a test message to a specified URL.
        
        This message contains the following payload with a signature in the `X-LVT-HMAC-SHA256` header so developers can test the validation process used in Webhook creation.
        ```json
        {
          "attempt": 1,
          "currentAttemptTimestamp": "<CURRENT_DATE_AS_ISO_8601_STRING>",
          "action": "test",
          "data": {
            "message": "Hello, world!"
          }
        }
        ```
      tags: [ Webhooks ]
  /publicKeys/{publicKeyId}:
    get:
      summary: Get a Public Key
      description: Get a Public Key with the provided ID.
      tags: [ PublicKeys ]
###############################################################################

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.lvt.com/oauth2/v1/token
          scopes:
            account.liveUnits.manage: Edit a live units data
            account.cameras.manage: Edit a cameras data
            account.locations.manage: Edit a locations data