openapi: 3.0.3
info:
  title: LVT API
  description: Public REST API - Beta
  version: 0.5.0
servers:
  - url: 'https://api.lvt.com/v1'
    description: Production beta version
security:
  - OAuth2: [ ]
tags:
  - name: Cameras
    description: Operations on cameras
  - name: LiveUnits
    description: Operations on LiveUnits
  - name: Locations
    description: Operations on locations

paths:
  /liveUnits:
    get:
      operationId: GetLiveUnits
      security:
        - OAuth2: [ account.liveUnits.manage ]
      tags:
        - LiveUnits
      summary: This endpoint returns all the live units accessible by the specified client.
      description: >
        **Phase 1**:
        List of liveUnits for the user's client
  /liveUnits/{liveUnitId}:
    get:
      operationId: GetLiveUnit
      security:
        - OAuth2: [ account.liveUnits.manage ]
      tags:
        - LiveUnits
      summary: Details for the specified live unit.
      description: >
        **Phase 1**:
        Details for the specified live unit.
  /liveUnits/{liveUnitId}/callInfo:
    get:
      operationId: GetLiveUnitCallInfo
      tags:
        - LiveUnits
      summary: Get information on how to make a call to the live unit
      description: >
        **Phase 2**: 
        Get information on how to make a call to the live unit
  /liveUnits/{liveUnitId}/cameras:
    get:
      operationId: GetLiveUnitCameras
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - LiveUnits
      summary: List of user accessible cameras hosted by the given liveUnit.
  /liveUnits/{liveUnitId}/sounds:
    get:
      operationId: GetLiveUnitSounds
      tags:
        - LiveUnits
      summary: List of quick sounds that can be played by the live unit
      description: >
        **Phase 3**:
        List of quick sounds that can be played by the live unit
  /liveUnits/{liveUnitId}/sounds/{soundId}:play:
    post:
      operationId: PlayLiveUnitSound
      tags:
        - LiveUnits
      summary: Play a quick sound from a live unit
      description: >
        **Phase 3**:
        Play a quick sound from a live unit
  /liveUnits/{liveUnitId}/lights:
    get:
      operationId: GetLiveUnitLights
      tags:
        - LiveUnits
      summary: List of lights on the live unit
      description: >
        **Phase 3**:
        List of lights on the live unit
  /liveUnits/{liveUnitId}/lights/{lightId}:toggle:
    post:
      operationId: ToggleLiveUnitLight
      tags:
        - LiveUnits
      summary: Toggle the status of a light on a live unit
      description: >
        **Phase 3**:
        Toggle the status of a light on a live unit
  /cameras/{cameraId}:
    get:
      operationId: GetLiveUnitCamera
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
      summary: Details of selected camera.
      description: >
        **Phase 1**:
        Details of selected camera.
  /cameras/{cameraId}/position:
    get:
      operationId: GetCameraPosition
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
      summary: Returns the selected camera's PTZF values
      description: >
        **Phase 1**:
        Returns the selected camera's PTZF values
    put:
      operationId: UpdateCameraPosition
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
      summary: Updates the selected camera's PTZF values
      description: >
        **Phase 1**:
        Updates a camera's PTZF
  /cameras/{cameraId}/protocols:
    get:
      operationId: GetProtocols
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
      summary: Returns list of protocols supported
      description: >
        **Phase 1**:
        Get list of protocols supported by this camera.
  /cameras/{cameraId}/streams:
    post:
      operationId: StartStream
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Cameras
        - Streams
      summary: Start a stream
      description: >
        **Phase 1**:
        Starts a stream and returns stream data for the camera
  /streams/{streamId}:checkIn:
    post:
      operationId: CheckIn
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Streams
      summary: Check in streaming for the camera
      description: >
        **Phase 1**:
        Check in streaming for the camera
  /streams/{streamId}:
    delete:
      operationId: CheckOut
      security:
        - OAuth2: [ account.cameras.manage ]
      tags:
        - Streams
      summary: Check out streaming for the camera
      description: >
        **Phase 1**:
        Check out streaming for the camera
  /locations:
    get:
      operationId: GetLocations
      security:
        - OAuth2: [ account.locations.manage ]
      tags:
        - Locations
      summary: List of locations for the user's client
      description: >
        **Phase 1**: 
        Returns all the locations accessible by the specified client.
  /locations/{locationId}:
    get:
      operationId: GetLocation
      security:
        - OAuth2: [ account.locations.manage ]
      tags:
        - Locations
      summary: Details for the specified location.
      description: >
        **Phase 1**:
        Details for the specified location.
  /locations/{locationId}/liveUnits:
    get:
      operationId: GetLocationLiveUnits
      security:
        - OAuth2: [ account.liveUnits.manage ]
      tags:
        - Locations
      summary: List of user accessible live units at the given location.
      description: >
        **Phase 1**:
        List of user accessible live units at the given location.
  /alerts:
    get:
      operationId: GetAlerts
      tags:
        - Alerts
      summary: Get all alerts a user has access to
      description: >
        **Phase 2**:
        Get all alerts a user has access to
  /alerts/types:
    get:
      operationId: GetAlertTypes
      tags:
        - Alerts
      summary: Get alert types
      description: >
        **Phase 2**:
        Get all valid enumeration types relevant to an alert.
        This includes alert causes, alert subjects (sub-classification of the "intrusion" alert cause), and resolution tags.
        <br/><br/>
        This endpoint will be mostly static however, as new values become supported they will be added to this response.
  /alerts/{alertId}:
    get:
      operationId: GetAlert
      tags:
        - Alerts
      summary: Get a single alert
      description: >
        **Phase 2**:
        Get a single alert
  /alerts/{alertId}:resolve:
    post:
      operationId: ResolveAlert
      tags:
        - Alerts
      summary: Resolve a single alert
      description: >
        **Phase 2**:
        Resolve a single alert
  /webhooks:
    post:
      operationId: CreateWebhook
      tags:
        - Webhooks
      summary: Register a new webhook to receive alerts
      description: >
        **Phase 4**:
        Register a new webhook to receive alerts
    get:
      operationId: GetWebhooks
      tags:
        - Webhooks
      summary: Get a list of registered webhooks
      description: >
        **Phase 4**:
        Get a list of registered webhooks
  /webhooks/{webhookId}:
    get:
      operationId: GetWebhook
      tags:
        - Webhooks
      summary: Get information about a single webhook
      description: >
        **Phase 4**:
        Get information about a single webhook
    patch:
      operationId: UpdateWebhook
      tags:
        - Webhooks
      summary: Update a webhook
      description: >
        **Phase 4**:
        Update a webhook
    delete:
      operationId: DeleteWebhook
      tags:
        - Webhooks
      summary: Delete a webhook
      description: >
        **Phase 4**:
        Delete a webhook
###############################################################################

components:
  securitySchemes:
    OAuth2:
      type: oauth2
      flows:
        clientCredentials:
          tokenUrl: https://api.lvt.com/oauth2/v1/token
          scopes:
            account.liveUnits.manage: Edit a live units data
            account.cameras.manage: Edit a cameras data
            account.locations.manage: Edit a locations data